######################################################################
# Automatically generated by qmake (3.0) ?? ??? 24 12:21:03 2015
######################################################################

TEMPLATE = app
TARGET = Project1
QT += widgets core gui
INCLUDEPATH += .

# Input
HEADERS += edge.h graphwidget.h MainWindow.h Node.h ui_MainWindow.h
FORMS += MainWindow.ui
SOURCES += edge.cpp graphwidget.cpp node.cpp Source.cpp
